[project]
name = "PyMCT"
version = "1.2.2"
authors = [
  { name="Yifei Ren", email="ryf0510@live.com" },
]
description = "A simple implement for MCTS algorithm."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = ["anytree", "unique_names_generator"]
[project.urls]
"Homepage" = "https://github.com/ulfaric/PyMCT"
"Bug Tracker" = "https://github.com/ulfaric/PyMCT/issues"

[tool.setuptools]
packages = ["PyMCT"]