[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "casper7-plugin-meatball-day"
version = "0.4.2"
description = ""
authors = ["backwardspy <backwardspy@gmail.com>"]
readme = "README.md"
packages = [{include = "casper7_plugin_meatball_day"}]

[tool.poetry.scripts]
casper7-plugin-meatball-day = "casper7_plugin_meatball_day.run:plugin"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.dependencies]
python = "^3.10"
piccolo = {extras = ["all"], version = "^0.96.0"}
docopt-ng = "^0.8.1"
pendulum = "^2.1.2"
pydantic = "^1.10.2"
platformdirs = "^2.5.3"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pylint = "^2.15.2"
mypy = "^0.971"
isort = "^5.10.1"
ipython = "^8.5.0"

[tool.isort]
profile = "black"
