[tool.poetry]
name = "telegram_parser"
version = "0.0.1"
description = "Parse Telegram Bot API"
authors = ["Arwichok <me@arwi.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
tp = 'telegram_parser.cli:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
