[tool.poetry]
name = "sarina"
version = "0.0.2"
description = ""
authors = ["Hadi <hadi.zolfaghaari@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "^4.60.0"
rich = "^12.6.0"
pyyaml = "^6.0"
python-digitalocean = "^1.17.0"
paramiko = "^2.12.0"
deepdiff = "^6.2.1"
tld = "^0.12.6"
inquirerpy = "^0.3.4"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
ipython = "^8.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sarina = 'sarina:main'