[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eodFunc"
version = "0.01"
authors = [
  { name="dylan marsella", email="dylanmarsella1@gmail.com" },
]
description = "work with the EODHistorical API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/dmars12345/eodFunc"
