[tool.poetry]
name = "clicom"
version = "0.0.3"
description = ""
authors = ["limonyellow"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.7.0"
colorama = {version = ">=0.4.3,<0.5.0", optional = true}
shellingham = {version = ">=1.3.0,<2.0.0", optional = true}
rich = {version = ">=10.11.0,<13.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
mkdocs-material = "^8.5.10"

[tool.poetry.extras]
all = [
    "colorama >=0.4.3,<0.5.0",
    "shellingham >=1.3.0,<2.0.0",
    "rich >=10.11.0,<13.0.0",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
