[tool.poetry]
name = "pagemap"
version = "0.1.1"
description = "A tool for virtual memory."
authors = ["fffzlfk <1319933925qq@gmail.com>"]
readme = "README.md"
keywords = ["pagemap", "maps", "linux"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pagemap = 'pagemap.entry:main'