[build-system]
requires = [ "setuptools", "setuptools-scm",]
build-backend = "setuptools.build_meta"

[project]
name = "hito_tools"
version = "22.10.1"
description = "Modules for interacting with Hito and NSIP"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [ "pandas", "requests",]
dynamic = []

[[project.authors]]
name = "Michel Jouvin"
email = "michel.jouvin@ijclab.in2p3.fr"


[tool]

[project.license]
text = "BSD 3-Clause License"

[project.urls]
Homepage = "https://gitlab.in2p3.fr/hito/hito_tools"
"Bug Tracker" = "https://gitlab.in2p3.fr/hito/hito_tools/-/issues"
