[tool.poetry]
name = "avotes-parser-cli"
version = "0.5.3"
description = "Aragon votings parser CLI"
authors = [
    "Dmitri Ivakhnenko <dmit.ivh@gmail.com>",
    "Eugene Mamin <thedzhon@gmail.com>",
    "Aleksei Potapkin <folkyatina@gmail.com>"
]
license = "MIT"
packages = [{ include = "avotes_parser" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
requests = "~2.28.1"
pysha3 = "~1.0.2"
eth-brownie = "~1.19.2"
web3 = "~5.31.1"
avotes-parser-core = "~0.5.3"

[tool.poetry.dev-dependencies]
tox = "~3.25.0"
pytest = "~6.2.5"
flake8 = "~4.0.1"

[tool.poetry.scripts]
avotes-parser = "avotes_parser.cli.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
