[tool.black]
line-length = 100
target-version = ['py310']

[build-system]
requires = ['setuptools>=45', 'wheel', 'setuptools_scm[toml]>=6.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'pyg3a'
version = '0.2.1'
authors = [
	{ name='dr_carlos', email='dr.steven.carlos@gmail.com' }
]
description = 'A tool to convert Python files to Casio fx-CG 10/20/50 (Prizm) Add-ins'
readme = 'README.md'
requires-python = '>=3.10'
dependencies = [
	'libcst >= 0.4.2'
]
classifiers = [
	'Development Status :: 4 - Beta',
	'Topic :: Software Development :: Build Tools',
	'Intended Audience :: Developers',
	'Programming Language :: Python :: 3.10',
	'License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)'
]

[project.urls]
'Homepage' = 'https://gitlab.com/dr_carlos/PyG3A'
'Bug Tracker' = 'https://gitlab.com/dr_carlos/PyG3A/-/issues'

[project.scripts]
pyg3a = "pyg3a:main"
