[tool.poetry]
name = "shell-helper-auth"
version = "0.2.0"
description = "Requests authentication using shell helpers"
readme = "README.md"
authors = ["Michal Porte≈° <michalportes1@gmail.com>"]
license = "MIT"
homepage = "https://github.com/mportesdev/shell-helper-auth"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2"

[tool.poetry.group.dev.dependencies]
pytest = "^7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
