[tool.poetry]
name = "dost"
version = "0.0.4"
readme = "README.md"
packages = [{include = "dost"}]
description = "DOST is a Python based Utility platform as an Open Source project. We strive to liberate humans from mundane, repetitive tasks, giving them more time to use their intellect and creativity to solve higher-order business challenges and perform knowledge work."
authors = ["PyBOTs <support@pybots.ai>"]
license = "MIT"
homepage = "https://pybots.ai"
repository = "https://github.com/py-bots/dost"
documentation = "https://py-bots.github.io/dost/"
keywords = ["PyBots","dost","my-dost","utility","Python","Automation", "Software BOT","Dost", "bots", "RPA"]
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: Education',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Financial and Insurance Industry',
    'Intended Audience :: Information Technology',
    'Intended Audience :: System Administrators',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: Python',
]

[tool.poetry.dependencies]
python = ">=3.9.0,<=3.10.40"
typeguard = "^2.13.3"
PyScreeze = "^0.1.28"
pywinauto = "^0.6.8"
Pillow = "^9.2.0"
PyPDF2 = "^2.11.0"
pyttsx3 = "^2.90"
pandas = "^1.5.0"
openpyxl = "^3.0.10"
xls2xlsx = "^0.1.5"
xlsx2html = "^0.4.0"
xlwt = "^1.3.0"
pygetwindow = "^0.0.9"
pytesseract = "^0.3.10"
yagmail = "^0.15.293"
pywhatkit = "^5.4"
phonenumbers = "^8.12.56"
barcode = "^1.0.2"
pyshorteners = "^1.0.1"
pytube = "^12.1.0"
imageio = "^2.22.1"
pyzbar = "^0.1.9"
PyQRCode = "^1.2.1"
geopy = "^2.2.0"
torch = [
  {url = "https://download.pytorch.org/whl/cpu/torch-1.10.0%2Bcpu-cp39-cp39-linux_x86_64.whl", markers = "sys_platform == 'linux'"},
  {url = "https://download.pytorch.org/whl/cpu/torch-1.10.0%2Bcpu-cp39-cp39-win_amd64.whl", markers = "sys_platform == 'win32'", python = "3.9.0"},
  {url = "https://download.pytorch.org/whl/cpu/torch-1.12.0%2Bcpu-cp310-cp310-win_amd64.whl", markers = "sys_platform == 'win32'", python = "3.10.0"},
]
easyocr = "^1.6.2"
invoice2data = "^0.3.6"
winshell = "^0.6"
opencv-python = "4.5.5.64"
requests = "^2.28.1"
gspread = "^5.6.2"
oauth2client = "^4.1.3"
gspread-dataframe = "^3.3.0"
pdfplumber = "^0.7.5"
countryinfo = "^0.1.2"
captcha = "^0.4"
WMI = "^1.5.1"
aspose-words = "^22.10.0"
plyer = "^2.0.0"
textblob = "^0.17.1"
speechrecognition = "^3.8.1"


[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
mkdocs-material = "^8.4.2"
mkdocstrings-python = "^0.7.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
ipykernel = "^6.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
