[tool.poetry]
name = "decorworld_database_model"
version = "0.1.0"
description = ""
authors = ["Pintér Tamás <tamas.pinter@pannonszoftver.hu>"]

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "1.3.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
