
[build-system]
  build-backend = "poetry.core.masonry.api"
  requires = ["poetry-core>=1.0.0"]

[tool]

  [tool.poetry]
    authors = ["CycAI Inc"]
    description = "The data-centric workspace for AI & DS"
    exclude = ["cnext_app/tsconfig.json", "cnext_app/README.md", "cnext_app/Dockerfile", "cnext_app/Dockerfile-poetry", "cnext_app/.dockerignore", "cnext_app/server/Dockerfile", "cnext_app/server/Dockerfile-conda", "cnext_app/server/.dockerignore"]
    homepage = "https://cyc-ai.com/"
    include = ["cnext_server/public/**/*"]
    license = "MIT"
    name = "cnext"
    readme = "README.md"
    version = "0.11.5"

    [tool.poetry.dependencies]
      cnextlib = "^0.7.0"
      jupyter-client = "~7.2.2"
      jupyter-resource-usage = "^0.6.1"
      jupyterlab = "~3.3.4"
      matplotlib = "~3.5.1"
      matplotlib-inline = "^0.1.6"
      mlflow = "^1.29.0"
      multipledispatch = "^0.6.0"
      netron = "^6.0.0"
      pandas = "~1.3.5"
      plotly = "~5.7.0"
      protobuf = "3.20.1"
      pyreadline = "^2.1"
      python = ">=3.9"
      python-language-server = "^0.36.2"
      pyyaml = "^5.1"
      pyzmq = "^23.2.0"
      requests = "^2.27.1"
      send2trash = "^1.8.0"
      sentry-sdk = "^1.5.12"
      simplejson = "^3.17.6"

    [tool.poetry.dev-dependencies]

    [[tool.poetry.packages]]
      include = "cnext_server"

    [tool.poetry.scripts]
      cnext = "cnext_server.__main__:main"
